name: boardvote
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  build_runner: ^2.4.12
  cloud_firestore: ^5.2.1
  dio: ^5.6.0
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  google_sign_in: ^6.2.1
  html_unescape: ^2.0.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  xml: ^6.5.0
  xml2json: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.2
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
